name: Auto Assign & Reviewers

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add reviewers & assignees
        uses: hkusu/review-assign-action@v1.4.0
        with:
          add-reviewers: true
          add-assignees: true
          reviewers: |
            ashubambal
            teamlead
          assignees: |
            ashubambal
          max-num-of-reviewers: 2
          max-num-of-assignees: 1
