name: Auto Assign Reviewer

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Assign reviewer
        uses:  hkusu/review-assign-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/auto_assign.yml
          reviewers: 'ashubambal'   # Replace with GitHub usernames
          number-of-reviewers: 1                        # Number of reviewers per PR
          addReviewers: true
          addAssignees: false