##############################
#  FILE 1: .github/workflows/auto-assign.yml
##############################
name: Auto Assign Reviewer and Assignee

on:
  pull_request_target:
    types: [opened, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/auto_assign.yml


##############################
#  FILE 2: .github/auto_assign.yml
##############################
addReviewers: true
addAssignees: true

reviewers:
  - "ashubambal"

assignees:
  - "ashubambal"

numberOfReviewers: 1
numberOfAssignees: 1
