name: Auto Assign & Reviewers

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Add Reviewers & Assignees
        uses: hkusu/review-assign-action@v1.4.0
        with:
          add-reviewers: true
          add-assignees: true
          reviewers: "ashubambal"
          assignees: "ashubambal"
          max-num-of-reviewers: 1
          max-num-of-assignees: 1
