name: Auto Assign Reviewers & Assignees

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  auto-assign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add Reviewers & Assignees
        uses: hkusu/review-assign-action@v1.4.0
        with:
          add-reviewers: true
          add-assignees: true

          reviewers: |
            Kalyani-Bambal
            ashubambal
            raj123

          assignees: |
            Kalyani-Bambal

          max-num-of-reviewers: 1
          max-num-of-assignees: 1
